using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ShokoRelay.Config
{
    public static class ConfigConstants
    {
        public const string ConfigFileName = "preferences.json";
        public const string SecretsFileName = "plex.token";
        public const string PluginSubfolder = "ShokoRelay";
        public const string DashboardSubfolder = "dashboard";
        public const string ConfigSubfolder = "config";
    }

    public enum SummaryMode
    {
        FullySanitize = 0,
        AllowInfoLines = 1,
        AllowMiscLines = 2,
        AllowBoth = 3,
    }

    public enum AudienceRatingMode
    {
        AniDB = 0,
        TMDB = 1,
        None = 2,
    }

    public enum MinimumTagWeight
    {
        Zero = 0,
        OneHundred = 100,
        TwoHundred = 200,
        ThreeHundred = 300,
        FourHundred = 400,
        FiveHundred = 500,
        SixHundred = 600,
    }

    public class RelayConfig
    {
        [Display(Name = "Series Title Language", Description = "Priority, comma separated")]
        [DefaultValue("SHOKO, X-JAT, EN")]
        public string SeriesTitleLanguage { get; set; } = "SHOKO, X-JAT, EN";

        [Display(Name = "Series Alt Title Language", Description = "Priority, comma separated")]
        [DefaultValue("EN, X-JAT, SHOKO")]
        public string SeriesAltTitleLanguage { get; set; } = "EN, X-JAT, SHOKO";

        [Display(Name = "Episode Title Language", Description = "Priority, comma separated")]
        [DefaultValue("SHOKO, EN, X-JAT")]
        public string EpisodeTitleLanguage { get; set; } = "SHOKO, EN, X-JAT";

        [Display(Name = "Move Common Series Title Prefixes", Description = "Enable to put 'Gekijouban', 'OVA', etc. at the end of the series title")]
        [DefaultValue(true)]
        public bool MoveCommonSeriesTitlePrefixes { get; set; } = true;

        [Display(Name = "Assumed Content Ratings", Description = "Enable to use content ratings and descriptors derived from AniDB tags")]
        [DefaultValue(true)]
        public bool AssumedContentRatings { get; set; } = true;

        [Display(Name = "Crew Listings", Description = "Enable staff listings in Plex's Cast & Crew section")]
        [DefaultValue(true)]
        public bool CrewListings { get; set; } = true;

        [Display(Name = "Collection Posters", Description = "Enable to use the primary series poster in a Shoko group for the collection poster")]
        [DefaultValue(true)]
        public bool CollectionPosters { get; set; } = true;

        [Display(Name = "Plex Theme Music", Description = "Enable to grab theme music files from Plex (uses TVDB IDs)")]
        [DefaultValue(true)]
        public bool PlexThemeMusic { get; set; } = true;

        [Display(Name = "TMDB Episode Numbering", Description = "Enable to prefer TMDB episode numbering when available (recommended)")]
        [DefaultValue(true)]
        public bool TMDBEpNumbering { get; set; } = true;

        [Display(Name = "TMDB Episode Group Names", Description = "Enable to prefer TMDB titles for grouped episodes (fixes duped titles)")]
        [DefaultValue(true)]
        public bool TMDBEpGroupNames { get; set; } = true;

        [Display(Name = "TMDB Season Posters", Description = "Enable to use TMDB season posters for multi-season series")]
        [DefaultValue(true)]
        public bool TMDBSeasonPosters { get; set; } = true;

        [Display(Name = "TMDB Thumbnails", Description = "Enable to use TMDB episode thumbnails instead of the ones generated by Plex")]
        [DefaultValue(false)]
        public bool TMDBThumbnails { get; set; } = false;

        [Display(Name = "Add Every Image", Description = "Enable to add all images instead of Shoko's preferred one (seasons always do)")]
        [DefaultValue(false)]
        public bool AddEveryImage { get; set; } = false;

        [Display(Name = "Summary Mode", Description = "Select the summary sanitization level")]
        [DefaultValue(SummaryMode.FullySanitize)]
        public SummaryMode SummaryMode { get; set; } = SummaryMode.FullySanitize;

        [Display(Name = "Audience Rating Mode", Description = "Select the preferred source for audience ratings in Plex")]
        [DefaultValue(AudienceRatingMode.AniDB)]
        public AudienceRatingMode AudienceRatingMode { get; set; } = AudienceRatingMode.AniDB;

        [Display(Name = "Minimum Tag Weight", Description = "Select the minimum AniDB tag weight to apply to a series in Plex")]
        [DefaultValue(MinimumTagWeight.Zero)]
        public MinimumTagWeight MinimumTagWeight { get; set; } = MinimumTagWeight.Zero;

        [Display(Name = "Tag Blacklist", Description = "A list of tags to exclude from series in Plex, comma separated")]
        [DefaultValue("")]
        public string TagBlacklist { get; set; } = "";

        [Display(Name = "Path Mappings", Description = "Mappings for Shoko base paths to Plex base paths")]
        public Dictionary<string, string> PathMappings { get; set; } = new();

        [Display(Name = "VFS Parallelism", Description = "The maximum concurrent series to process during VFS builds")]
        [DefaultValue(4)]
        public int VfsParallelism { get; set; } = 4;

        [Display(Name = "VFS Root Path", Description = "The location of the virtual links inside each import root")]
        [DefaultValue("!ShokoRelayVFS")]
        public string VfsRootPath { get; set; } = "!ShokoRelayVFS";

        [Display(Name = "Collection Posters Root Path", Description = "The location of custom local collection posters inside each import root")]
        [DefaultValue("!CollectionPosters")]
        public string CollectionPostersRootPath { get; set; } = "!CollectionPosters";

        [Display(Name = "AnimeThemes Root Path", Description = "The location of AnimeThemes .webm files inside each import root")]
        [DefaultValue("!AnimeThemes")]
        public string AnimeThemesRootPath { get; set; } = "!AnimeThemes";

        [Display(Name = "AnimeThemes Path Mapping", Description = "The base path containing AnimeThemes .webm files for mapping generation")]
        [DefaultValue("/animethemes/")]
        public string AnimeThemesPathMapping { get; set; } = "/animethemes/";

        [Display(Name = "FFmpeg Path", Description = "An optional folder containing FFmpeg/FFprobe. Leave empty to use the plugin root or PATH")]
        [DefaultValue("")]
        public string FFmpegPath { get; set; } = "";

        [Display(Name = "Plex Auth", Description = "Plex device registration settings for Plex authentication")]
        [Browsable(false)]
        public PlexAuthConfig PlexAuth { get; set; } = new();

        [Display(Name = "Plex Library", Description = "Plex server connection settings for refresh and collections")]
        [Browsable(false)]
        public PlexLibraryConfig PlexLibrary { get; set; } = new();

        [Display(Name = "Extra Plex Users", Description = "Comma-separated Plex usernames (stored in preferences.json)")]
        [Browsable(false)]
        [DefaultValue("")]
        public string ExtraPlexUsers { get; set; } = "";

        [Display(Name = "Shoko API Key", Description = "API key for Shoko Server v3 API (used for scheduled/manual imports). Stored in preferences.json")]
        [Browsable(false)]
        [DefaultValue("")]
        public string ShokoApiKey { get; set; } = string.Empty;

        [Display(Name = "Auto Import Frequency (hours)", Description = "Run Shoko import detection every N hours. Set to 0 to disable")]
        [Browsable(false)]
        [DefaultValue(0)]
        public int ShokoImportFrequencyHours { get; set; } = 0;

        [Display(Name = "Auto Sync Watched Frequency (hours)", Description = "Run watched-state sync every N hours. Set to 0 to disable")]
        [Browsable(false)]
        [DefaultValue(0)]
        public int ShokoSyncWatchedFrequencyHours { get; set; } = 0;

        [Display(Name = "Include Ratings for Scheduled Sync", Description = "When enabled, scheduled Plex->Shoko sync will also include user ratings/votes")]
        [Browsable(false)]
        [DefaultValue(false)]
        public bool ShokoSyncWatchedIncludeRatings { get; set; } = false;

        [Display(Name = "Auto Scrobble", Description = "Enable instant scrobble handling from Plex webhooks (media.scrobble)")]
        [Browsable(false)]
        [DefaultValue(false)]
        public bool AutoScrobble { get; set; } = false;
    }

    public class RelaySecrets
    {
        public PlexAuthSecrets PlexAuth { get; set; } = new();

        public bool IsEmpty => PlexAuth.IsEmpty;
    }

    public class PlexAuthSecrets
    {
        public string ClientIdentifier { get; set; } = "";

        public bool IsEmpty => string.IsNullOrWhiteSpace(ClientIdentifier);
    }
}
